### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by andylauxing** [yueyueniao2012/SlidingMenu#1]
新手求问：请问这个项目andorid版本？要4.0以上吗?能否具体说说安装步骤？便于像我一样的新手学习，谢谢。

**Comment by yueyueniao2012** [comment]
you can install this app by this step:eclipse menu-->File-->new-->project-->Android project from existing code with sdk>8(android2.2).

**Comment by andylauxing** [comment]
你好，按照你的提示，导入项目还是有错：
The import com.actionbarsherlock cannot be resolved
请问这是要导入哪个jar包?

**Comment by andylauxing** [comment]
对了，我用的SDK版本是:android2.2

**Comment by andylauxing** [comment]
还有一个配置文件style.xml报错(出现红叉叉)

 <item name="android:homeAsUpIndicator">@drawable/new_indicator</item>

error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock.Light.DarkActionBar'.

**Comment by andylauxing** [comment]
![slidmenu01](https://f.cloud.github.com/assets/3881256/286246/a281ae8e-9237-11e2-8d8b-9d246c5dac3b.gif)
![slideMenu02](https://f.cloud.github.com/assets/3881256/286251/c3bc4208-9237-11e2-928b-1351f69fc4fe.gif)

**Comment by yueyueniao2012** [comment]
不好意思，你是在哪里下的这个项目，貌似不是我的项目，请重新下载
